### ISSUE TITLE
mod_python does not start pyntlm

### ISSUE THREAD

**Issue by hcf** [Legrandin/PyAuthenNTLM2#14]
> Ensure that mod-python can find pyntlm.py. You should be able to see the following line for each a request, if the log level is set to Info.
> [info] [client 127.0.0.1] PYNTLM: Handling connection 0x0 from address 127.0.0.1 for GET URI /mysite/request

We are not seeing this in our logs, but the troubleshooting section doesn't help much in regards to how to debug this problem. mod_python is starting

> [notice] mod_python: Creating 8 session mutexes based on 256 max processes and 0 max threads.

but we are not seeing any PYNTLM logging, and our users are not getting any WWW-Authenticate: NTLM header. Any ideas what might be wrong?

Configuration file:

```
<VirtualHost *:80>
  ServerName XXX
  ProxyPreserveHost on
  KeepAlive On

  <Location />
    AuthType NTLM
    AuthName "Log in with username and password"
    require valid-user

    PythonAuthenHandler pyntlm
    PythonOption Domain TESTZONE2
    PythonOption PDC [IP 1]
    PythonOption BDC [IP 2]
  </Location>

  LogLevel debug
</VirtualHost>
```

Setup:
- CentOS release 5.9 (Final)
- Python 2.4.3
- Apache 2.2.3
- mod_python from github
- pycrypto from github
- PyAuthenNTLM2 from github

**Comment by hcf** [comment]
Notice to self. In your quest to make NTLMv2 work, do not have two modules that try to handle NTLM authentication at the same time...

**Comment by DeathR0W** [comment]
Hi, I am getting problem with valid-user for 2.4 and I dont know how to solve it.. were you able to fix this issue?
