### ISSUE TITLE
Intermittent 401 Authorization required error

### ISSUE THREAD

**Issue by zenmedia** [Legrandin/PyAuthenNTLM2#16]
When using PyAuthenNTLM2 master branch, we have a web app which utilises javascript post requests fairly heavily.

If we hit the site normally and trigger the ajax call shortly afterwards I get a log message [Tue Dec 17 15:28:14 2013] [notice] [client 127.0.0.1] PYNTLM: User Joe.Bloggs/TESTDOMAIN has been authenticated to access URI /search, referer: http://broken.site.domain/

If I leave a short period of time before I trigger any ajax calls, the above message is added to the log in first instance, but I get prompted for a Basic Authentication box which wont go away.

This happens in all web browsers.

Can anyone shine any light on this?

Thanks

**Comment by zenmedia** [comment]
After raising the log method there is a new message of .. Spurious authentic ation request on connection 0x1. 

and

[Tue Dec 17 15:43:33 2013] [info] [client 127.0.0.1] Unexpected NTLM message Type 3 in new connection for URI /search, referer: http://broken.site.domain/

**Comment by zenmedia** [comment]
Found method to resolve issue in #12

**Comment by akovacs123** [comment]
I have absolutely the same problem. I auth user vith PyAuthNTLM2 successfully. However, I have a flash player in my website calling HTTP API calls using POSTs. An auth Window pops up several times (each every POST!), so I have to reauthenticate. I wonder if anyone knows a solution.
