### ISSUE TITLE
Can't install on Python 2.4

### ISSUE THREAD

**Issue by mbeijen** [Legrandin/PyAuthenNTLM2#2]
Hi, 

First of all, I don't know anything about Python, really.
I wanted to deploy your script on a RHEL 5 based machine and found out it would not install because it requires Python 2.6, and RHEL 5 has 2.4; is it correct that it will not work on RHEL5's python?
## Would it be feasible to get this also to work on Python 2.4? 

Mike

**Comment by Legrandin** [comment]
Hi Mike,

There is nothing special that requires Python 2.6 (the only version I tested it with), so it is definitely feasible to make it work with 2.4.

I have just checked in a few changes that I know should help to run in 2.4.
I have not time right now to verify them at all though.
If you don't mind, you can try them and let me know which error you get (hopefully none!).

**Comment by mapa3m** [comment]
Mike,

I'm running this module on stock Python 2.4 on RHEL5. What problems are you seeing?

Legrandin - just wanted to say, great module, really helped me out!

**Comment by mapa3m** [comment]
Oh, one note for Python 2.4 - PythonAuthenHandler should be set to "pyntlm" instead of full path:

PythonAuthenHandler   pyntlm

**Comment by Legrandin** [comment]
Tested on python 2.4 too and it works fine.

**Comment by scott-r-lindsey** [comment]
I just installed this on a CentOS box w/2.4 and it worked.  SO MUCH WIN!
